pia.webclient:
  basic:
    firstBasic:
      connection-provider-name: firstBasic
      fixed-headers:
        header1: value1
      token-config:
        username: user1
        password: pass1
    secondBasic:
      connection-provider-name: secondBasic
      fixed-headers:
        header1: value1
        header2: value2
      token-config:
        username: user2
        password: pass2
  openid:
    firstOpenId:
      connection-provider-name: firstOpenId
      fixed-headers:
        header1: value1
      token-config:
        use-mock: false
        token-url: http://localhost:1080/token
        basicAuthUsername: user
        basicAuthPassword: pass
        cache-expiry-seconds: 1
        username-field: username
        form-data:
          username: user
          password: pass
          scope: openid
          grant_type: password
    secondOpenId:
      connection-provider-name: secondOpenId
      fixed-headers:
        header1: value1
        header2: value2
      token-config:
        use-mock: false
        token-url: http://localhost:1080/token
        basicAuthUsername: user
        basicAuthPassword: pass
        cache-expiry-seconds: 1
        username-field: username
        form-data:
          username: user
          password: pass
          scope: openid
          grant_type: password
